version: "3.7"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: book
    container_name: app-book
    working_dir: /var/www/app
    volumes:
      - ./app/:/var/www/app
    networks:
      - book
  db:
    image: mysql:5.7
    container_name: db-book
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_PASSWORD:password
    volumes:
      - db:/var/lib/mysql
    networks:
      - book
  nginx:
    image: nginx:alpine
    container_name: nginx-book
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - book
networks:
  book:
    driver: bridge
volumes:
  db:
    driver: local
